### ISSUE TITLE
Jud. xvi., 17

### ISSUE THREAD

**Issue by rccreswell** [rcw5890/bochus#9]
https://github.com/rcw5890/bochus/blob/b77c3e292dfdfa000094f9d2a53696fb8b26a0e0/books/jocelin_cronica/main.tex#L545

16:19 (ab eo fortitudo) seems to be a better fit. If so, the location of their footnote is also mistaken.

**Comment by jcreswell** [comment]
Jocelin's "recessit ab eo fortitudo eius" echoes the Vulgate in both 16:17 ("recedet a me fortitudo mea") and 16:19 ("ab eo fortitudo discessit"), but the corresponding English is "his strength went from him". "Thus was Samson mocked" ("Et sic illusus est Samson") does not seem to be a quotation.
